---
- name: GitLab CE telepítése
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: GitLab repo script letöltése és futtatása
      shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
      args:
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list

    - name: GitLab CE telepítése
      apt:
        name: gitlab-ce
        state: present
      environment:
        EXTERNAL_URL: "https://{{ gitlab_domain }}"
        # GitLab saját beépített Nginx-et és Let's Encrypt-et használ
        # A mi Nginx-ünk NEM kezeli a gitlab_domain-t

    - name: GitLab konfigurálása
      command: gitlab-ctl reconfigure
      args:
        creates: /var/opt/gitlab/bootstrapped
